name: Compile

on:
    push:

jobs:
    compile:
        name: Compile
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Install dependencies
              run: deno task install

            - name: Cache dependencies
              run: deno task cache

            - name: Compile
              run: deno task compile
